//auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const OPERATOR_ISNOT_ADMIN_ERROR = "OPERATOR_ISNOT_ADMIN_ERROR";
export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";
export const CLEAR_PASSWORD_RESET_ERROR="CLEAR_PASSWORD_RESET_ERROR";

//work order
export const GET_ALL_WORK_ORDERS = " GET_ALL_WORK_ORDERS";
export const GET_WORK_ORDER = "GET_WORK_ORDER";
export const DELETE_WORK_ORDER = "DELETE_WORK_ORDER";
export const GET_VARIANTS = "GET_VARIANTS";
export const GET_ASSEMBLY_LINE = "GET_ASSEMBLY_LINE";
export const ASSIGN_GET_WORK_ORDER = "ASSIGN_GET_WORK_ORDER";
export const SET_PAGE_CHANGE = "SET_PAGE_CHANGE";
export const SAVE_WORK_ORDER_SUCCESS = "SAVE_WORK_ORDER_SUCCESS";
export const UPLOAD_WORK_ORDER_SUCCESS = "UPLOAD_WORK_ORDER_SUCCESS";
export const UPLOAD_VARIANT_SUCCESS = "UPLOAD_VARIANT_SUCCESS";
export const MARK_ALL_WORK_ORDER_AS_COMPLETE =
  "MARK_ALL_WORK_ORDER_AS_COMPLETE";
export const MARK_COMPLETE_DELETE_WORK_ORDER_SUCCESS =
  "MARK_COMPLETE_DELETE_WORK_ORDER_SUCCESS";

//masterData
export const GET_ALL_COMPONENTS = "GET_ALL_COMPONENTS";
export const GET_ALL_VARIANTS = "GET_ALL_VARIANTS";
export const GET_ALL_OPERATIONS = "GET_ALL_OPERATIONS";
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const GET_ALL_SOP = "GET_ALL_SOP";
export const GET_ALL_COMPONENTS_FOR_DROPDOWN =
  "GET_ALL_COMPONENTS_FOR_DROPDOWN";
export const SAVE_SUCCESSFULLY = "SAVE_SUCCESSFULLY";
export const GET_COMPONENT_IMAGE_BY_ID = "GET_COMPONENT_IMAGE_BY_ID";
export const GET_VARIANT_IMAGE_BY_ID = "GET_VARIANT_IMAGE_BY_ID";
export const GOT_GI_FILE_URL = "GOT_GI_FILE_URL";
export const GOT_SOP_FILE_URL = "GOT_SOP_FILE_URL";
export const GET_BOM_BY_VARIANT_ID = "GET_BOM_BY_VARIANT_ID";
export const GET_SOP_BY_VARIANT_ID = "GET_SOP_BY_VARIANT_ID";

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_LOCATION_LIST = "GET_ALL_USER_LOCATION_LIST";
export const DELETE_USER_SUCCESSFULLY = "DELETE_USER_SUCCESSFULLY";

//loading
export const SET_LOADING = "SET_LOADING";
export const SAVE_LOCATION_SUCCESSFULLY = "SAVE_LOCATION_SUCCESSFULLY";
export const SAVE_COMPONENT_SUCCESSFULLY = "SAVE_COMPONENT_SUCCESSFULLY";
export const SAVE_VARIANT_SUCCESSFULLY = "SAVE_VARIANT_SUCCESSFULLY";
export const SAVE_OPERATION_SUCCESSFULLY = "SAVE_OPERATION_SUCCESSFULLY";

//delete
export const OPERATION_DELETE_SUCCESSFULLY = "OPERATION_DELETE_SUCCESSFULLY";
export const DELETE_COMPONENT_SUCCESSFULLY = "DELETE_COMPONENT_SUCCESSFULLY";
export const DELETE_LOCATION_SUCCESSFULLY = "DELETE_LOCATION_SUCCESSFULLY";
export const DELETE_VARIANT_SUCCESSFULLY = "DELETE_VARIANT_SUCCESSFULLY";

//feedback
export const GET_ALL_FEEDBACK = "GET_ALL_FEEDBACK";
export const FEEDBACK_RESOLVE_SUCCESSFULLY = "FEEDBACK_RESOLVE_SUCCESSFULLY";
export const FEEDBACK_ESCALATE_SUCCESSFULLY = "FEEDBACK_ESCALATE_SUCCESSFULLY";

//error
export const GET_ERROR = "GET_ERROR";
export const PAGE_LOADING = "PAGE_LOADING";
